// angular-version/src/app/components/about-section/about-section.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslationService } from '../../services/translation.service';
import { ScrollAnimationDirective } from '../../directives/scroll-animation.directive';

@Component({
  selector: 'app-about-section',
  standalone: true,
  imports: [CommonModule, ScrollAnimationDirective],
  template: `
    <section id="about" class="relative py-24 overflow-hidden">
      <!-- Background -->
      <div class="absolute inset-0">
        <div class="absolute inset-0 bg-gradient-to-br from-slate-900 via-slate-800 to-cyan-900"></div>
        <div class="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?auto=format&fit=crop&w=2000&q=80')] bg-cover bg-center opacity-10"></div>
        <div class="absolute top-0 left-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl"></div>
        <div class="absolute bottom-0 right-1/4 w-80 h-80 bg-teal-500/10 rounded-full blur-3xl"></div>
      </div>

      <div class="container mx-auto px-4 relative z-10">
        <!-- Section Header -->
        <div class="text-center mb-16" appScrollAnimation animationType="fade-up">
          <span class="inline-block px-4 py-2 bg-cyan-500/20 text-cyan-300 rounded-full text-sm font-medium mb-4 border border-cyan-500/30">
            {{ t('about.title') }}
          </span>
          <h2 class="text-4xl md:text-5xl font-bold text-white mb-4">
            {{ t('about.subtitle') }}
          </h2>
        </div>

        <!-- Main Content -->
        <div class="grid lg:grid-cols-2 gap-12 items-center mb-16">
          <!-- Image Side -->
          <div class="relative" appScrollAnimation animationType="fade-right">
            <div class="absolute -inset-4 bg-gradient-to-r from-cyan-500 to-teal-500 rounded-2xl blur-2xl opacity-20"></div>
            <div class="relative rounded-2xl overflow-hidden shadow-2xl">
              <img 
                src="https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1000&q=80"
                alt="Food trade warehouse"
                class="w-full h-80 lg:h-[500px] object-cover"
              />
              <div class="absolute inset-0 bg-gradient-to-t from-slate-900/80 via-transparent to-transparent"></div>
              <div class="absolute bottom-6 left-6 right-6">
                <div class="flex items-center gap-4">
                  <div class="flex -space-x-2">
                    <div class="w-10 h-10 rounded-full bg-gradient-to-r from-cyan-500 to-teal-500 flex items-center justify-center text-white font-bold text-sm border-2 border-white">10+</div>
                  </div>
                  <div>
                    <p class="text-white font-semibold">Years of Experience</p>
                    <p class="text-white/70 text-sm">International Trade</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Text Side -->
          <div class="space-y-6" appScrollAnimation animationType="fade-left">
            <p class="text-lg text-white/80 leading-relaxed">
              {{ t('about.description') }}
            </p>

            <!-- Stats Grid -->
            <div class="grid grid-cols-2 gap-4 pt-4">
              @for (stat of stats; track stat.value) {
                <div class="p-4 bg-white/5 backdrop-blur-sm rounded-xl border border-white/10">
                  <div class="text-3xl font-bold text-cyan-400 mb-1">{{ stat.value }}</div>
                  <div class="text-white/70 text-sm">{{ stat.label }}</div>
                </div>
              }
            </div>
          </div>
        </div>

        <!-- Values Cards -->
        <div class="grid md:grid-cols-3 gap-6">
          @for (card of valueCards; track card.titleKey; let i = $index) {
            <div 
              class="group p-6 bg-white/5 backdrop-blur-sm rounded-2xl border border-white/10 hover:border-cyan-500/50 hover:bg-white/10 transition-all duration-500"
              appScrollAnimation 
              animationType="fade-up"
              [animationDelay]="i * 100">
              <div class="w-14 h-14 rounded-xl bg-gradient-to-br from-cyan-500 to-teal-500 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300">
                <svg class="w-7 h-7 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" [innerHTML]="card.icon"></svg>
              </div>
              <h3 class="text-xl font-bold text-white mb-2">{{ t(card.titleKey) }}</h3>
              <p class="text-white/70 leading-relaxed">{{ t(card.textKey) }}</p>
            </div>
          }
        </div>
      </div>
    </section>
  `,
  styles: [`
    :host {
      display: block;
    }
  `]
})
export class AboutSectionComponent {
  private translationService = inject(TranslationService);

  stats = [
    { value: '50+', label: 'Partners Worldwide' },
    { value: '20+', label: 'Countries Served' },
    { value: '1000+', label: 'Tons Exported' },
    { value: '100%', label: 'Quality Certified' }
  ];

  valueCards = [
    {
      titleKey: 'about.mission.title',
      textKey: 'about.mission.text',
      icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>'
    },
    {
      titleKey: 'about.vision.title',
      textKey: 'about.vision.text',
      icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>'
    },
    {
      titleKey: 'about.values.title',
      textKey: 'about.values.text',
      icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"/>'
    }
  ];

  t(key: string): string {
    return this.translationService.t(key);
  }
}

// components/about-section.tsx
'use client';

import Image from 'next/image';
import { Target, Eye, Heart, Globe, Ship, Award } from 'lucide-react';
import { useLanguage } from '@/lib/language-context';
import { useScrollAnimation } from '@/hooks/use-scroll-animation';

export function AboutSection() {
  const { t } = useLanguage();
  const { ref: sectionRef, isVisible: sectionVisible } = useScrollAnimation<HTMLElement>();
  const { ref: cardsRef, isVisible: cardsVisible } = useScrollAnimation<HTMLDivElement>();

  const values = [
    {
      icon: Target,
      title: t.about.mission.title,
      text: t.about.mission.text,
    },
    {
      icon: Eye,
      title: t.about.vision.title,
      text: t.about.vision.text,
    },
    {
      icon: Heart,
      title: t.about.values.title,
      text: t.about.values.text,
    },
  ];

  const stats = [
    { icon: Globe, value: '15+', label: 'Countries' },
    { icon: Ship, value: '500+', label: 'Shipments/Year' },
    { icon: Award, value: '10+', label: 'Years Experience' },
  ];

  return (
    <section
      id="about"
      ref={sectionRef}
      className="relative py-28 overflow-hidden"
    >
      {/* Background with gradient and pattern */}
      <div className="absolute inset-0 bg-gradient-to-b from-background via-muted/30 to-background" />
      <div className="absolute inset-0 opacity-[0.02]" style={{ backgroundImage: 'url("data:image/svg+xml,%3Csvg width="60" height="60" viewBox="0 0 60 60" xmlns="http://www.w3.org/2000/svg"%3E%3Cg fill="none" fill-rule="evenodd"%3E%3Cg fill="%23000000" fill-opacity="1"%3E%3Cpath d="M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z"/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")' }} />
      
      <div className="container mx-auto px-4 relative z-10">
        {/* Section Header */}
        <div
          className={`text-center mb-20 transition-all duration-700 ${
            sectionVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'
          }`}
        >
          <span className="inline-block px-4 py-2 bg-primary/10 text-primary rounded-full text-sm font-medium mb-4 tracking-wide">
            {t.nav.about}
          </span>
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold text-foreground mb-6 tracking-tight">
            {t.about.title}
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            {t.about.subtitle}
          </p>
        </div>

        {/* Content Grid */}
        <div className="grid lg:grid-cols-2 gap-16 items-center mb-24">
          {/* Image Stack */}
          <div
            className={`relative transition-all duration-1000 delay-200 ${
              sectionVisible ? 'translate-x-0 opacity-100' : '-translate-x-20 opacity-0'
            }`}
          >
            {/* Main Image */}
            <div className="relative h-[450px] lg:h-[550px] rounded-3xl overflow-hidden shadow-2xl">
              <Image
                src="https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80"
                alt="Import Export Operations"
                fill
                className="object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-tr from-primary/40 via-transparent to-transparent" />
            </div>
            
            {/* Floating secondary image */}
            <div className="absolute -bottom-8 -right-8 w-48 h-48 md:w-64 md:h-64 rounded-2xl overflow-hidden shadow-2xl border-4 border-background hidden md:block">
              <Image
                src="https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400&q=80"
                alt="Food Products"
                fill
                className="object-cover"
              />
            </div>
            
            {/* Stats Badge */}
            <div className="absolute -top-6 -right-6 bg-gradient-to-br from-primary to-primary/80 text-primary-foreground p-6 rounded-2xl shadow-2xl shadow-primary/30 hidden lg:block">
              <p className="text-5xl font-bold">10+</p>
              <p className="text-sm opacity-90">
                {t.about.subtitle.includes('confiance') || t.about.subtitle.includes('trust')
                  ? 'Years of Excellence'
                  : 'Años de Excelencia'}
              </p>
            </div>
          </div>

          {/* Text Content */}
          <div
            className={`transition-all duration-1000 delay-400 ${
              sectionVisible ? 'translate-x-0 opacity-100' : 'translate-x-20 opacity-0'
            }`}
          >
            <p className="text-lg text-muted-foreground leading-relaxed mb-10">
              {t.about.description}
            </p>
            
            {/* Mini Stats */}
            <div className="grid grid-cols-3 gap-4 mb-10">
              {stats.map((stat, index) => (
                <div
                  key={index}
                  className="text-center p-4 rounded-2xl bg-card border border-border hover:border-primary/30 transition-colors"
                >
                  <stat.icon className="h-6 w-6 text-primary mx-auto mb-2" />
                  <p className="text-2xl font-bold text-foreground">{stat.value}</p>
                  <p className="text-xs text-muted-foreground">{stat.label}</p>
                </div>
              ))}
            </div>
            
            <div className="space-y-6">
              {values.slice(0, 2).map((item, index) => (
                <div key={index} className="flex gap-5 items-start group">
                  <div className="p-4 bg-gradient-to-br from-primary/10 to-primary/5 rounded-xl group-hover:from-primary/20 group-hover:to-primary/10 transition-colors">
                    <item.icon className="h-6 w-6 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-foreground text-lg mb-1">{item.title}</h3>
                    <p className="text-muted-foreground leading-relaxed">{item.text}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Values Cards */}
        <div
          ref={cardsRef}
          className="grid md:grid-cols-3 gap-8"
        >
          {values.map((item, index) => (
            <div
              key={index}
              className={`group relative bg-card p-8 rounded-3xl border border-border hover:border-primary/30 transition-all duration-500 hover:-translate-y-3 hover:shadow-2xl hover:shadow-primary/10 overflow-hidden ${
                cardsVisible
                  ? 'translate-y-0 opacity-100'
                  : 'translate-y-10 opacity-0'
              }`}
              style={{ transitionDelay: `${index * 150}ms` }}
            >
              {/* Decorative gradient blob */}
              <div className="absolute -top-20 -right-20 w-40 h-40 bg-primary/10 rounded-full blur-3xl group-hover:bg-primary/20 transition-colors" />
              
              <div className="relative z-10">
                <div className="p-4 bg-gradient-to-br from-primary/15 to-primary/5 rounded-2xl w-fit mb-6 group-hover:from-primary/25 group-hover:to-primary/10 transition-colors">
                  <item.icon className="h-8 w-8 text-primary" />
                </div>
                <h3 className="text-xl font-semibold text-foreground mb-3">
                  {item.title}
                </h3>
                <p className="text-muted-foreground leading-relaxed">
                  {item.text}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
