// angular-version/src/app/components/hero-section/hero-section.component.ts
import { Component, inject, signal, OnInit, OnDestroy, PLATFORM_ID } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { TranslationService } from '../../services/translation.service';

interface Slide {
  image: string;
  titleKey: string;
  subtitleKey: string;
}

@Component({
  selector: 'app-hero-section',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section id="home" class="relative min-h-screen flex items-center justify-center overflow-hidden">
      <!-- Background Slides -->
      @for (slide of slides; track slide.titleKey; let i = $index) {
        <div 
          class="absolute inset-0 transition-opacity duration-1000"
          [class.opacity-100]="currentSlide() === i"
          [class.opacity-0]="currentSlide() !== i">
          <img 
            [src]="slide.image" 
            [alt]="t(slide.titleKey)"
            class="w-full h-full object-cover"
          />
          <div class="absolute inset-0 bg-gradient-to-b from-slate-900/80 via-slate-900/60 to-slate-900/90"></div>
          <div class="absolute inset-0 bg-gradient-to-r from-cyan-900/30 to-teal-900/30"></div>
        </div>
      }

      <!-- Decorative Elements -->
      <div class="absolute top-1/4 left-10 w-72 h-72 bg-cyan-500/10 rounded-full blur-3xl animate-pulse"></div>
      <div class="absolute bottom-1/4 right-10 w-96 h-96 bg-teal-500/10 rounded-full blur-3xl animate-pulse" style="animation-delay: 1s"></div>

      <!-- Content -->
      <div class="relative z-10 container mx-auto px-4 text-center">
        <div class="max-w-4xl mx-auto">
          <!-- Badge -->
          <div class="inline-flex items-center gap-2 px-4 py-2 bg-white/10 backdrop-blur-sm rounded-full border border-white/20 mb-8 animate-fade-in-up">
            <span class="w-2 h-2 bg-cyan-400 rounded-full animate-pulse"></span>
            <span class="text-cyan-300 text-sm font-medium tracking-wide">Import & Export Food Products</span>
          </div>

          <!-- Title -->
          <h1 class="text-4xl md:text-6xl lg:text-7xl font-bold text-white mb-6 leading-tight animate-fade-in-up" style="animation-delay: 0.2s">
            {{ t(slides[currentSlide()].titleKey) }}
          </h1>

          <!-- Subtitle -->
          <p class="text-lg md:text-xl text-white/80 mb-10 max-w-2xl mx-auto leading-relaxed animate-fade-in-up" style="animation-delay: 0.4s">
            {{ t(slides[currentSlide()].subtitleKey) }}
          </p>

          <!-- CTAs -->
          <div class="flex flex-col sm:flex-row gap-4 justify-center animate-fade-in-up" style="animation-delay: 0.6s">
            <a 
              href="#products"
              class="group inline-flex items-center justify-center gap-2 px-8 py-4 bg-gradient-to-r from-cyan-500 to-teal-500 text-white font-semibold rounded-full shadow-lg shadow-cyan-500/25 hover:shadow-cyan-500/40 hover:scale-105 transition-all duration-300">
              {{ t('hero.cta.primary') }}
              <svg class="w-5 h-5 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
              </svg>
            </a>
            <a 
              href="#contact"
              class="inline-flex items-center justify-center gap-2 px-8 py-4 bg-white/10 backdrop-blur-sm text-white font-semibold rounded-full border-2 border-white/30 hover:bg-white/20 hover:border-white/50 transition-all duration-300">
              {{ t('hero.cta.secondary') }}
            </a>
          </div>
        </div>
      </div>

      <!-- Slide Indicators -->
      <div class="absolute bottom-10 left-1/2 -translate-x-1/2 flex gap-3 z-10">
        @for (slide of slides; track slide.titleKey; let i = $index) {
          <button 
            (click)="goToSlide(i)"
            class="group relative w-12 h-2 rounded-full overflow-hidden bg-white/20 hover:bg-white/30 transition-colors duration-300">
            <div 
              class="absolute inset-y-0 left-0 bg-gradient-to-r from-cyan-400 to-teal-400 rounded-full transition-all duration-300"
              [style.width]="currentSlide() === i ? '100%' : '0%'">
            </div>
          </button>
        }
      </div>

      <!-- Navigation Arrows -->
      <button 
        (click)="prevSlide()"
        class="absolute left-4 md:left-10 top-1/2 -translate-y-1/2 p-3 rounded-full bg-white/10 backdrop-blur-sm border border-white/20 text-white hover:bg-white/20 transition-all duration-300 z-10">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
        </svg>
      </button>
      <button 
        (click)="nextSlide()"
        class="absolute right-4 md:right-10 top-1/2 -translate-y-1/2 p-3 rounded-full bg-white/10 backdrop-blur-sm border border-white/20 text-white hover:bg-white/20 transition-all duration-300 z-10">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
        </svg>
      </button>

      <!-- Scroll Indicator -->
      <div class="absolute bottom-32 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 animate-bounce">
        <span class="text-white/50 text-xs uppercase tracking-widest">Scroll</span>
        <svg class="w-5 h-5 text-white/50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 14l-7 7m0 0l-7-7m7 7V3"/>
        </svg>
      </div>
    </section>
  `,
  styles: [`
    :host {
      display: block;
    }
    .animate-fade-in-up {
      animation: fadeInUp 0.8s ease-out forwards;
    }
    @keyframes fadeInUp {
      from {
        opacity: 0;
        transform: translateY(30px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }
  `]
})
export class HeroSectionComponent implements OnInit, OnDestroy {
  private translationService = inject(TranslationService);
  private platformId = inject(PLATFORM_ID);
  private intervalId: ReturnType<typeof setInterval> | null = null;

  currentSlide = signal(0);

  slides: Slide[] = [
    {
      image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=2000&q=80',
      titleKey: 'hero.slide1.title',
      subtitleKey: 'hero.slide1.subtitle'
    },
    {
      image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=2000&q=80',
      titleKey: 'hero.slide2.title',
      subtitleKey: 'hero.slide2.subtitle'
    },
    {
      image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=2000&q=80',
      titleKey: 'hero.slide3.title',
      subtitleKey: 'hero.slide3.subtitle'
    }
  ];

  ngOnInit(): void {
    if (isPlatformBrowser(this.platformId)) {
      this.startAutoSlide();
    }
  }

  ngOnDestroy(): void {
    this.stopAutoSlide();
  }

  t(key: string): string {
    return this.translationService.t(key);
  }

  startAutoSlide(): void {
    this.intervalId = setInterval(() => {
      this.nextSlide();
    }, 6000);
  }

  stopAutoSlide(): void {
    if (this.intervalId) {
      clearInterval(this.intervalId);
    }
  }

  goToSlide(index: number): void {
    this.currentSlide.set(index);
    this.stopAutoSlide();
    this.startAutoSlide();
  }

  nextSlide(): void {
    this.currentSlide.update(v => (v + 1) % this.slides.length);
  }

  prevSlide(): void {
    this.currentSlide.update(v => (v - 1 + this.slides.length) % this.slides.length);
    this.stopAutoSlide();
    this.startAutoSlide();
  }
}

// components/hero-section.tsx
'use client';

import { useState, useEffect, useCallback } from 'react';
import { ChevronLeft, ChevronRight, ArrowDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/lib/language-context';

const slides = [
  {
    key: 'slide1',
    image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=1920&q=80',
  },
  {
    key: 'slide2',
    image: 'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=1920&q=80',
  },
  {
    key: 'slide3',
    image: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=1920&q=80',
  },
];

export function HeroSection() {
  const { t } = useLanguage();
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isAnimating, setIsAnimating] = useState(false);

  const nextSlide = useCallback(() => {
    if (isAnimating) return;
    setIsAnimating(true);
    setCurrentSlide((prev) => (prev + 1) % slides.length);
    setTimeout(() => setIsAnimating(false), 700);
  }, [isAnimating]);

  const prevSlide = useCallback(() => {
    if (isAnimating) return;
    setIsAnimating(true);
    setCurrentSlide((prev) => (prev - 1 + slides.length) % slides.length);
    setTimeout(() => setIsAnimating(false), 700);
  }, [isAnimating]);

  useEffect(() => {
    const interval = setInterval(nextSlide, 6000);
    return () => clearInterval(interval);
  }, [nextSlide]);

  const getSlideContent = (key: string) => {
    const heroContent = t.hero as Record<string, { title: string; subtitle: string; cta: string }>;
    return heroContent[key] || { title: '', subtitle: '', cta: '' };
  };

  const handleScrollToProducts = () => {
    const element = document.querySelector('#products');
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  const handleScrollToAbout = () => {
    const element = document.querySelector('#about');
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  const handleScrollToContact = () => {
    const element = document.querySelector('#contact');
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  const ctaActions = [handleScrollToProducts, handleScrollToAbout, handleScrollToContact];

  return (
    <section id="home" className="relative h-screen w-full overflow-hidden">
      {/* Slides */}
      {slides.map((slide, index) => {
        const content = getSlideContent(slide.key);
        return (
          <div
            key={slide.key}
            className={`absolute inset-0 transition-all duration-700 ease-in-out ${
              index === currentSlide ? 'opacity-100 z-10 scale-100' : 'opacity-0 z-0 scale-105'
            }`}
          >
            {/* Background Image with Ken Burns effect */}
            <div
              className={`absolute inset-0 bg-cover bg-center transition-transform duration-[8000ms] ease-linear ${
                index === currentSlide ? 'scale-110' : 'scale-100'
              }`}
              style={{ backgroundImage: `url(${slide.image})` }}
            />
            {/* Dark Overlay with gradient */}
            <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/70" />
            <div className="absolute inset-0 bg-gradient-to-r from-primary/20 via-transparent to-transparent" />

            {/* Content */}
            <div className="relative z-20 h-full flex items-center justify-center">
              <div className="container mx-auto px-4 text-center">
                {/* Decorative line */}
                <div
                  className={`w-20 h-1 bg-primary mx-auto mb-8 transition-all duration-700 ${
                    index === currentSlide
                      ? 'scale-x-100 opacity-100'
                      : 'scale-x-0 opacity-0'
                  }`}
                  style={{ transitionDelay: '50ms' }}
                />
                <h1
                  className={`text-4xl md:text-6xl lg:text-7xl font-bold text-white mb-6 transition-all duration-700 text-balance tracking-tight ${
                    index === currentSlide
                      ? 'translate-y-0 opacity-100'
                      : 'translate-y-10 opacity-0'
                  }`}
                  style={{ transitionDelay: '100ms', textShadow: '2px 4px 12px rgba(0,0,0,0.4)' }}
                >
                  {content.title}
                </h1>
                <p
                  className={`text-lg md:text-xl lg:text-2xl text-white/90 mb-10 max-w-3xl mx-auto transition-all duration-700 text-pretty font-light ${
                    index === currentSlide
                      ? 'translate-y-0 opacity-100'
                      : 'translate-y-10 opacity-0'
                  }`}
                  style={{ transitionDelay: '200ms', textShadow: '1px 2px 8px rgba(0,0,0,0.3)' }}
                >
                  {content.subtitle}
                </p>
                <div
                  className={`flex flex-col sm:flex-row gap-4 justify-center transition-all duration-700 ${
                    index === currentSlide
                      ? 'translate-y-0 opacity-100'
                      : 'translate-y-10 opacity-0'
                  }`}
                  style={{ transitionDelay: '300ms' }}
                >
                  <Button
                    size="lg"
                    onClick={ctaActions[index]}
                    className="bg-primary hover:bg-primary/90 text-primary-foreground text-lg px-10 py-7 shadow-lg shadow-primary/30 hover:shadow-xl hover:shadow-primary/40 transition-all duration-300 hover:-translate-y-1"
                  >
                    {content.cta}
                  </Button>
                  <Button
                    size="lg"
                    variant="outline"
                    onClick={handleScrollToContact}
                    className="border-2 border-white/50 text-white bg-white/10 backdrop-blur-sm hover:bg-white/20 hover:border-white text-lg px-10 py-7 transition-all duration-300 hover:-translate-y-1"
                  >
                    {t.nav.contact}
                  </Button>
                </div>
              </div>
            </div>
          </div>
        );
      })}

      {/* Navigation Arrows */}
      <button
        onClick={prevSlide}
        className="absolute left-6 top-1/2 -translate-y-1/2 z-30 p-4 bg-white/5 hover:bg-white/15 backdrop-blur-md rounded-full transition-all duration-300 border border-white/10 hover:border-white/30 group"
        aria-label="Previous slide"
      >
        <ChevronLeft className="h-6 w-6 text-white group-hover:scale-110 transition-transform" />
      </button>
      <button
        onClick={nextSlide}
        className="absolute right-6 top-1/2 -translate-y-1/2 z-30 p-4 bg-white/5 hover:bg-white/15 backdrop-blur-md rounded-full transition-all duration-300 border border-white/10 hover:border-white/30 group"
        aria-label="Next slide"
      >
        <ChevronRight className="h-6 w-6 text-white group-hover:scale-110 transition-transform" />
      </button>

      {/* Slide Indicators */}
      <div className="absolute bottom-28 left-1/2 -translate-x-1/2 z-30 flex gap-3">
        {slides.map((_, index) => (
          <button
            key={index}
            onClick={() => setCurrentSlide(index)}
            className={`h-2 rounded-full transition-all duration-500 ${
              index === currentSlide
                ? 'bg-primary w-12'
                : 'bg-white/40 hover:bg-white/60 w-2'
            }`}
            aria-label={`Go to slide ${index + 1}`}
          />
        ))}
      </div>

      {/* Scroll Down Indicator */}
      <div className="absolute bottom-10 left-1/2 -translate-x-1/2 z-30">
        <button
          onClick={handleScrollToAbout}
          className="flex flex-col items-center gap-2 text-white/70 hover:text-white transition-colors group"
          aria-label="Scroll to content"
        >
          <span className="text-sm font-light tracking-widest uppercase">Scroll</span>
          <div className="w-6 h-10 border-2 border-white/30 rounded-full flex justify-center pt-2 group-hover:border-white/60 transition-colors">
            <div className="w-1 h-3 bg-white/70 rounded-full animate-bounce" />
          </div>
        </button>
      </div>

      {/* Bottom gradient fade */}
      <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-background to-transparent z-20 pointer-events-none" />
    </section>
  );
}
