// components/contact-section.tsx
'use client';

import { useState } from 'react';
import Image from 'next/image';
import { MapPin, Phone, Mail, Clock, Send, CheckCircle, AlertCircle, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/lib/language-context';
import { useScrollAnimation } from '@/hooks/use-scroll-animation';

export function ContactSection() {
  const { t } = useLanguage();
  const [formState, setFormState] = useState({
    name: '',
    email: '',
    phone: '',
    subject: '',
    message: '',
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const { ref: sectionRef, isVisible: sectionVisible } = useScrollAnimation<HTMLElement>();
  const { ref: formRef, isVisible: formVisible } = useScrollAnimation<HTMLDivElement>();

  const validateEmail = (email: string) => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    // Client-side validation
    if (!formState.name || formState.name.length < 2) {
      setError('Please enter your name (at least 2 characters).');
      return;
    }

    if (!validateEmail(formState.email)) {
      setError('Please enter a valid email address.');
      return;
    }

    if (!formState.message || formState.message.length < 10) {
      setError('Please enter a message (at least 10 characters).');
      return;
    }

    setIsSubmitting(true);

    try {
      const response = await fetch('/api/contact', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formState),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to send message');
      }

      setIsSubmitted(true);
      setFormState({
        name: '',
        email: '',
        phone: '',
        subject: '',
        message: '',
      });

      setTimeout(() => setIsSubmitted(false), 5000);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to send message. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setError(null);
    setFormState((prev) => ({
      ...prev,
      [e.target.name]: e.target.value,
    }));
  };

  const contactInfo = [
    {
      icon: MapPin,
      label: t.contact.info.address,
      value: 'Madrid, España',
    },
    {
      icon: Phone,
      label: t.contact.info.phone,
      value: '+34 XXX XXX XXX',
    },
    {
      icon: Mail,
      label: t.contact.info.email,
      value: 'info@korianituna.com',
    },
    {
      icon: Clock,
      label: t.contact.info.hours,
      value: t.contact.info.hoursValue,
    },
  ];

  return (
    <section
      id="contact"
      ref={sectionRef}
      className="relative py-28 overflow-hidden"
    >
      {/* Background with gradient */}
      <div className="absolute inset-0 bg-gradient-to-b from-background via-muted/20 to-background" />
      
      {/* Background image with overlay */}
      <div className="absolute inset-0 opacity-5">
        <Image
          src="https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=1920&q=80"
          alt="Background"
          fill
          className="object-cover"
        />
      </div>
      
      <div className="container mx-auto px-4 relative z-10">
        {/* Section Header */}
        <div
          className={`text-center mb-20 transition-all duration-700 ${
            sectionVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'
          }`}
        >
          <span className="inline-block px-4 py-2 bg-primary/10 text-primary rounded-full text-sm font-medium mb-4 tracking-wide">
            {t.nav.contact}
          </span>
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold text-foreground mb-6 tracking-tight">
            {t.contact.title}
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            {t.contact.subtitle}
          </p>
        </div>

        <div
          ref={formRef}
          className="grid lg:grid-cols-5 gap-12 max-w-6xl mx-auto"
        >
          {/* Contact Form - Takes 3 columns */}
          <div
            className={`lg:col-span-3 bg-card rounded-3xl shadow-2xl border border-border p-8 md:p-10 transition-all duration-700 ${
              formVisible ? 'translate-x-0 opacity-100' : '-translate-x-10 opacity-0'
            }`}
          >
            {isSubmitted ? (
              <div className="flex flex-col items-center justify-center h-full py-16 text-center">
                <div className="w-20 h-20 bg-green-500/20 rounded-full flex items-center justify-center mb-6">
                  <CheckCircle className="h-10 w-10 text-green-500" />
                </div>
                <h3 className="text-2xl font-bold text-foreground mb-3">
                  {t.contact.form.success}
                </h3>
                <p className="text-muted-foreground">
                  {t.contact.subtitle.includes('responderemos') 
                    ? 'Le responderemos lo antes posible.'
                    : t.contact.subtitle.includes('répondrons')
                    ? 'Nous vous répondrons dans les plus brefs délais.'
                    : 'We will get back to you as soon as possible.'}
                </p>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-6">
                {error && (
                  <div className="flex items-center gap-3 p-4 bg-destructive/10 border border-destructive/30 rounded-xl text-destructive">
                    <AlertCircle className="h-5 w-5 flex-shrink-0" />
                    <p className="text-sm">{error}</p>
                  </div>
                )}
                
                <div className="grid md:grid-cols-2 gap-6">
                  <div>
                    <label
                      htmlFor="name"
                      className="block text-sm font-medium text-foreground mb-2"
                    >
                      {t.contact.form.name} <span className="text-destructive">*</span>
                    </label>
                    <input
                      type="text"
                      id="name"
                      name="name"
                      value={formState.name}
                      onChange={handleChange}
                      required
                      minLength={2}
                      className="w-full px-5 py-4 bg-muted/50 border border-border rounded-xl focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all text-foreground placeholder:text-muted-foreground"
                      placeholder="John Doe"
                    />
                  </div>
                  <div>
                    <label
                      htmlFor="email"
                      className="block text-sm font-medium text-foreground mb-2"
                    >
                      {t.contact.form.email} <span className="text-destructive">*</span>
                    </label>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      value={formState.email}
                      onChange={handleChange}
                      required
                      className="w-full px-5 py-4 bg-muted/50 border border-border rounded-xl focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all text-foreground placeholder:text-muted-foreground"
                      placeholder="john@example.com"
                    />
                  </div>
                </div>

                <div className="grid md:grid-cols-2 gap-6">
                  <div>
                    <label
                      htmlFor="phone"
                      className="block text-sm font-medium text-foreground mb-2"
                    >
                      {t.contact.form.phone}
                    </label>
                    <input
                      type="tel"
                      id="phone"
                      name="phone"
                      value={formState.phone}
                      onChange={handleChange}
                      className="w-full px-5 py-4 bg-muted/50 border border-border rounded-xl focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all text-foreground placeholder:text-muted-foreground"
                      placeholder="+34 XXX XXX XXX"
                    />
                  </div>
                  <div>
                    <label
                      htmlFor="subject"
                      className="block text-sm font-medium text-foreground mb-2"
                    >
                      {t.contact.form.subject}
                    </label>
                    <input
                      type="text"
                      id="subject"
                      name="subject"
                      value={formState.subject}
                      onChange={handleChange}
                      className="w-full px-5 py-4 bg-muted/50 border border-border rounded-xl focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all text-foreground placeholder:text-muted-foreground"
                      placeholder="Product Inquiry"
                    />
                  </div>
                </div>

                <div>
                  <label
                    htmlFor="message"
                    className="block text-sm font-medium text-foreground mb-2"
                  >
                    {t.contact.form.message} <span className="text-destructive">*</span>
                  </label>
                  <textarea
                    id="message"
                    name="message"
                    rows={5}
                    value={formState.message}
                    onChange={handleChange}
                    required
                    minLength={10}
                    className="w-full px-5 py-4 bg-muted/50 border border-border rounded-xl focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all resize-none text-foreground placeholder:text-muted-foreground"
                    placeholder={t.contact.subtitle.includes('responderemos') 
                      ? 'Escriba su mensaje aquí...'
                      : t.contact.subtitle.includes('répondrons')
                      ? 'Écrivez votre message ici...'
                      : 'Write your message here...'}
                  />
                </div>

                <Button
                  type="submit"
                  size="lg"
                  className="w-full py-6 text-lg shadow-lg shadow-primary/30 hover:shadow-xl hover:shadow-primary/40 transition-all"
                  disabled={isSubmitting}
                >
                  {isSubmitting ? (
                    <>
                      <Loader2 className="h-5 w-5 mr-2 animate-spin" />
                      {t.contact.form.sending}
                    </>
                  ) : (
                    <>
                      <Send className="h-5 w-5 mr-2" />
                      {t.contact.form.submit}
                    </>
                  )}
                </Button>
              </form>
            )}
          </div>

          {/* Contact Info - Takes 2 columns */}
          <div
            className={`lg:col-span-2 transition-all duration-700 delay-200 ${
              formVisible ? 'translate-x-0 opacity-100' : 'translate-x-10 opacity-0'
            }`}
          >
            {/* Info Card with gradient background */}
            <div className="relative overflow-hidden rounded-3xl h-full">
              {/* Background image */}
              <div className="absolute inset-0">
                <Image
                  src="https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&q=80"
                  alt="Contact Background"
                  fill
                  className="object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-br from-primary/95 via-primary/90 to-[#0a4a5c]/95" />
              </div>
              
              <div className="relative z-10 p-8 md:p-10 h-full flex flex-col">
                <h3 className="text-2xl font-bold text-white mb-8">{t.contact.subtitle}</h3>
                
                <div className="space-y-6 flex-grow">
                  {contactInfo.map((item, index) => (
                    <div key={index} className="flex items-start gap-4 group">
                      <div className="p-3 bg-white/10 rounded-xl group-hover:bg-white/20 transition-colors">
                        <item.icon className="h-6 w-6 text-white" />
                      </div>
                      <div>
                        <p className="text-sm text-white/70 mb-1">{item.label}</p>
                        <p className="font-medium text-white">{item.value}</p>
                      </div>
                    </div>
                  ))}
                </div>
                
                {/* Decorative element */}
                <div className="mt-8 pt-8 border-t border-white/20">
                  <p className="text-white/80 text-sm leading-relaxed">
                    {t.contact.subtitle.includes('responderemos') 
                      ? 'Estamos comprometidos a responder todas las consultas dentro de las 24 horas hábiles.'
                      : t.contact.subtitle.includes('répondrons')
                      ? 'Nous nous engageons à répondre à toutes les demandes dans les 24 heures ouvrables.'
                      : 'We are committed to responding to all inquiries within 24 business hours.'}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// angular-version/src/app/components/contact-section/contact-section.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TranslationService } from '../../services/translation.service';
import { ContactService } from '../../services/contact.service';
import { ScrollAnimationDirective } from '../../directives/scroll-animation.directive';

interface ContactForm {
  name: string;
  email: string;
  message: string;
}

interface FormErrors {
  name?: string;
  email?: string;
  message?: string;
}

@Component({
  selector: 'app-contact-section',
  standalone: true,
  imports: [CommonModule, FormsModule, ScrollAnimationDirective],
  template: `
    <section id="contact" class="relative py-24 overflow-hidden">
      <!-- Background -->
      <div class="absolute inset-0">
        <div class="absolute inset-0 bg-gradient-to-br from-slate-900 via-slate-800 to-cyan-900"></div>
        <div class="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=2000&q=80')] bg-cover bg-center opacity-10"></div>
        <div class="absolute bottom-0 left-0 w-full h-1/2 bg-gradient-to-t from-slate-900 to-transparent"></div>
      </div>

      <div class="container mx-auto px-4 relative z-10">
        <!-- Section Header -->
        <div class="text-center mb-16" appScrollAnimation animationType="fade-up">
          <span class="inline-block px-4 py-2 bg-cyan-500/20 text-cyan-300 rounded-full text-sm font-medium mb-4 border border-cyan-500/30">
            {{ t('contact.title') }}
          </span>
          <h2 class="text-4xl md:text-5xl font-bold text-white mb-4">
            {{ t('contact.subtitle') }}
          </h2>
        </div>

        <div class="grid lg:grid-cols-2 gap-12 max-w-6xl mx-auto">
          <!-- Contact Form -->
          <div 
            class="bg-white/5 backdrop-blur-sm rounded-2xl border border-white/10 p-8"
            appScrollAnimation 
            animationType="fade-right">
            <form (ngSubmit)="onSubmit()" class="space-y-6">
              <!-- Name -->
              <div>
                <label class="block text-white font-medium mb-2">{{ t('contact.form.name') }} *</label>
                <input 
                  type="text"
                  [(ngModel)]="form.name"
                  name="name"
                  [placeholder]="t('contact.form.name')"
                  class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white placeholder-white/50 focus:outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/20 transition-all duration-300"
                  [class.border-red-400]="errors().name"
                />
                @if (errors().name) {
                  <p class="mt-1 text-red-400 text-sm">{{ errors().name }}</p>
                }
              </div>

              <!-- Email -->
              <div>
                <label class="block text-white font-medium mb-2">{{ t('contact.form.email') }} *</label>
                <input 
                  type="email"
                  [(ngModel)]="form.email"
                  name="email"
                  [placeholder]="t('contact.form.email')"
                  class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white placeholder-white/50 focus:outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/20 transition-all duration-300"
                  [class.border-red-400]="errors().email"
                />
                @if (errors().email) {
                  <p class="mt-1 text-red-400 text-sm">{{ errors().email }}</p>
                }
              </div>

              <!-- Message -->
              <div>
                <label class="block text-white font-medium mb-2">{{ t('contact.form.message') }} *</label>
                <textarea 
                  [(ngModel)]="form.message"
                  name="message"
                  rows="5"
                  [placeholder]="t('contact.form.message')"
                  class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white placeholder-white/50 focus:outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/20 transition-all duration-300 resize-none"
                  [class.border-red-400]="errors().message">
                </textarea>
                @if (errors().message) {
                  <p class="mt-1 text-red-400 text-sm">{{ errors().message }}</p>
                }
              </div>

              <!-- Success/Error Messages -->
              @if (successMessage()) {
                <div class="p-4 bg-green-500/20 border border-green-500/30 rounded-xl text-green-300">
                  {{ successMessage() }}
                </div>
              }
              @if (errorMessage()) {
                <div class="p-4 bg-red-500/20 border border-red-500/30 rounded-xl text-red-300">
                  {{ errorMessage() }}
                </div>
              }

              <!-- Submit Button -->
              <button 
                type="submit"
                [disabled]="isSubmitting()"
                class="w-full px-8 py-4 bg-gradient-to-r from-cyan-500 to-teal-500 text-white font-semibold rounded-xl shadow-lg shadow-cyan-500/25 hover:shadow-cyan-500/40 hover:scale-[1.02] transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100">
                @if (isSubmitting()) {
                  <span class="flex items-center justify-center gap-2">
                    <svg class="animate-spin h-5 w-5" viewBox="0 0 24 24">
                      <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" fill="none"/>
                      <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"/>
                    </svg>
                    {{ t('contact.form.sending') }}
                  </span>
                } @else {
                  {{ t('contact.form.submit') }}
                }
              </button>
            </form>
          </div>

          <!-- Contact Info -->
          <div 
            class="space-y-8"
            appScrollAnimation 
            animationType="fade-left">
            <div>
              <h3 class="text-2xl font-bold text-white mb-6">{{ t('contact.info.title') }}</h3>
              <p class="text-white/70 mb-8">
                {{ t('footer.description') }}
              </p>
            </div>

            <!-- Info Cards -->
            <div class="space-y-4">
              @for (info of contactInfo; track info.labelKey) {
                <div class="flex items-start gap-4 p-4 bg-white/5 backdrop-blur-sm rounded-xl border border-white/10 hover:border-cyan-500/30 transition-colors duration-300">
                  <div class="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-500 to-teal-500 flex items-center justify-center flex-shrink-0">
                    <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" [innerHTML]="info.icon"></svg>
                  </div>
                  <div>
                    <p class="text-white font-medium">{{ t(info.labelKey) }}</p>
                    <p class="text-white/70">{{ info.value }}</p>
                  </div>
                </div>
              }
            </div>
          </div>
        </div>
      </div>
    </section>
  `,
  styles: [`
    :host {
      display: block;
    }
  `]
})
export class ContactSectionComponent {
  private translationService = inject(TranslationService);
  private contactService = inject(ContactService);

  form: ContactForm = {
    name: '',
    email: '',
    message: ''
  };

  errors = signal<FormErrors>({});
  isSubmitting = signal(false);
  successMessage = signal('');
  errorMessage = signal('');

  contactInfo = [
    {
      labelKey: 'contact.info.address',
      value: 'Madrid, España',
      icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/>'
    },
    {
      labelKey: 'contact.info.phone',
      value: '+34 XXX XXX XXX',
      icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"/>'
    },
    {
      labelKey: 'contact.info.email',
      value: 'info&#64;korianituna.com',
      icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/>'
    },
    {
      labelKey: 'contact.info.hours',
      value: 'Lun - Vie: 9:00 - 18:00',
      icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>'
    }
  ];

  t(key: string): string {
    return this.translationService.t(key);
  }

  validateForm(): boolean {
    const newErrors: FormErrors = {};

    if (!this.form.name.trim()) {
      newErrors.name = this.t('validation.required');
    }

    if (!this.form.email.trim()) {
      newErrors.email = this.t('validation.required');
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.form.email)) {
      newErrors.email = this.t('validation.email');
    }

    if (!this.form.message.trim()) {
      newErrors.message = this.t('validation.required');
    } else if (this.form.message.trim().length < 10) {
      newErrors.message = this.t('validation.minLength');
    }

    this.errors.set(newErrors);
    return Object.keys(newErrors).length === 0;
  }

  onSubmit(): void {
    this.successMessage.set('');
    this.errorMessage.set('');

    if (!this.validateForm()) return;

    this.isSubmitting.set(true);

    this.contactService.sendMessage(this.form).subscribe({
      next: (response) => {
        this.isSubmitting.set(false);
        if (response.success) {
          this.successMessage.set(this.t('contact.form.success'));
          this.form = { name: '', email: '', message: '' };
        } else {
          this.errorMessage.set(response.error || this.t('contact.form.error'));
        }
      },
      error: () => {
        this.isSubmitting.set(false);
        this.errorMessage.set(this.t('contact.form.error'));
      }
    });
  }
}
